In [58]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [59]:
## Encoder ---> Transform Categorical Data into Numerical Data
# (1) --> LabelEncoder
# (2) --> OrdinalEncoder
# (3) --> OneHotEncoder
# (4) --> pd.get_dummies()

In [60]:
df = pd.read_csv("Data/toyota.csv")
df.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [61]:
df.describe()

              year         price  ...          mpg   engineSize
count  6738.000000   6738.000000  ...  6738.000000  6738.000000
mean   2016.748145  12522.391066  ...    63.042223     1.471297
std       2.204062   6345.017587  ...    15.836710     0.436159
min    1998.000000    850.000000  ...     2.800000     0.000000
25%    2016.000000   8290.000000  ...    55.400000     1.000000
50%    2017.000000  10795.000000  ...    62.800000     1.500000
75%    2018.000000  14995.000000  ...    69.000000     1.800000
max    2020.000000  59995.000000  ...   235.000000     4.500000

[8 rows x 6 columns]

In [62]:
df = df.drop(columns= ['model'])
df.head()

   year  price transmission  mileage fuelType  tax   mpg  engineSize
0  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [63]:
df.isnull().sum()

year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [64]:
df['transmission'].value_counts()

transmission
Manual       3826
Automatic    2657
Semi-Auto     254
Other           1
Name: count, dtype: int64

## Label Encoder

In [65]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['transmission'] = lb.fit_transform(df['transmission'])
df.head()

   year  price  transmission  mileage fuelType  tax   mpg  engineSize
0  2016  16000             1    24089   Petrol  265  36.2         2.0
1  2017  15995             1    18615   Petrol  145  36.2         2.0
2  2015  13998             1    27469   Petrol  265  36.2         2.0
3  2017  18998             1    14736   Petrol  150  36.2         2.0
4  2017  17498             1    36284   Petrol  145  36.2         2.0

In [66]:
df['transmission'].value_counts()

transmission
1    3826
0    2657
3     254
2       1
Name: count, dtype: int64

In [67]:
df['fuelType'] = lb.fit_transform(df['fuelType'])
df.head()

   year  price  transmission  mileage  fuelType  tax   mpg  engineSize
0  2016  16000             1    24089         3  265  36.2         2.0
1  2017  15995             1    18615         3  145  36.2         2.0
2  2015  13998             1    27469         3  265  36.2         2.0
3  2017  18998             1    14736         3  150  36.2         2.0
4  2017  17498             1    36284         3  145  36.2         2.0

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          6738 non-null   int64
 1   price         6738 non-null   int64
 2   transmission  6738 non-null   int64
 3   mileage       6738 non-null   int64
 4   fuelType      6738 non-null   int64
 5   tax           6738 non-null   int64
 6   mpg           6738 non-null   float64
 7   engineSize    6738 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 421.3 KB

## OrdinalEncoder

In [69]:
df = pd.read_csv("Data/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [70]:
df['city'].unique()

<StringArray>
['Kolkata', 'Delhi', 'Mumbai', 'Bangalore']
Length: 4, dtype: str

In [71]:
df['gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [72]:
df = df.drop(columns= ['age', 'fever'])
df.head()

   gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [73]:
from sklearn.preprocessing import OrdinalEncoder

ode_gender = OrdinalEncoder(categories= [["Male", "Female"]])
df['gender'] = ode_gender.fit_transform(df[['gender']])
df.head()

   gender cough     city has_covid
0     0.0  Mild  Kolkata        No
1     0.0  Mild    Delhi       Yes
2     0.0  Mild    Delhi        No
3     1.0  Mild  Kolkata        No
4     1.0  Mild   Mumbai        No

In [74]:
ode = OrdinalEncoder(categories= [["Mild", "Strong"], ["Kolkata", "Bangalore", "Delhi", "Mumbai"], ["Yes", "No"]])

df[["cough", "city", "has_covid"]] = ode.fit_transform(df[["cough", "city", "has_covid"]])

df.head()

   gender  cough  city  has_covid
0     0.0    0.0   0.0        1.0
1     0.0    0.0   2.0        0.0
2     0.0    0.0   2.0        1.0
3     1.0    0.0   0.0        1.0
4     1.0    0.0   3.0        1.0

## MinMaxScaler

In [75]:
df = pd.read_csv("Data/toyota.csv")
df.head()

   model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [76]:
df = df.drop(columns = ['model'])
df.head()

   year  price transmission  mileage fuelType  tax   mpg  engineSize
0  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2  2015  13998       Manual    27469   Petrol  265  36.2         2.0
3  2017  18998       Manual    14736   Petrol  150  36.2         2.0
4  2017  17498       Manual    36284   Petrol  145  36.2         2.0

In [77]:
df['fuelType'].unique()

<StringArray>
['Petrol', 'Other', 'Hybrid', 'Diesel']
Length: 4, dtype: str

In [78]:
from sklearn.preprocessing import OrdinalEncoder

ode = OrdinalEncoder(categories= [['Manual', 'Automatic', 'Semi-Auto', 'Other'], ['Petrol', 'Other', 'Hybrid', 'Diesel']])

df[['transmission', 'fuelType']] = ode.fit_transform(df[['transmission', 'fuelType']])
df.head()

   year  price  transmission  mileage  fuelType  tax   mpg  engineSize
0  2016  16000           0.0    24089       0.0  265  36.2         2.0
1  2017  15995           0.0    18615       0.0  145  36.2         2.0
2  2015  13998           0.0    27469       0.0  265  36.2         2.0
3  2017  18998           0.0    14736       0.0  150  36.2         2.0
4  2017  17498           0.0    36284       0.0  145  36.2         2.0

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          6738 non-null   int64
 1   price         6738 non-null   int64
 2   transmission  6738 non-null   float64
 3   mileage       6738 non-null   int64
 4   fuelType      6738 non-null   float64
 5   tax           6738 non-null   int64
 6   mpg           6738 non-null   float64
 7   engineSize    6738 non-null   float64
dtypes: float64(4), int64(4)
memory usage: 421.3 KB

In [80]:
df.describe()

              year         price  ...          mpg   engineSize
count  6738.000000   6738.000000  ...  6738.000000  6738.000000
mean   2016.748145  12522.391066  ...    63.042223     1.471297
std       2.204062   6345.017587  ...    15.836710     0.436159
min    1998.000000    850.000000  ...     2.800000     0.000000
25%    2016.000000   8290.000000  ...    55.400000     1.000000
50%    2017.000000  10795.000000  ...    62.800000     1.500000
75%    2018.000000  14995.000000  ...    69.000000     1.800000
max    2020.000000  59995.000000  ...   235.000000     4.500000

[8 rows x 8 columns]

In [83]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

X = minmax_scaler.fit_transform(df)

df = pd.DataFrame(X, columns= df.columns)
df.describe()

              year        price  ...          mpg   engineSize
count  6738.000000  6738.000000  ...  6738.000000  6738.000000
mean      0.852188     0.197352  ...     0.259441     0.326955
std       0.100185     0.107279  ...     0.068203     0.096924
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.818182     0.125793  ...     0.226529     0.222222
50%       0.863636     0.168146  ...     0.258398     0.333333
75%       0.909091     0.239158  ...     0.285099     0.400000
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 8 columns]