## OneHotEncoder

In [28]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv("Data/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [37]:
from sklearn.preprocessing import OneHotEncoder
## Gender = 2 ---> 2-1 =1
# city = 4 ---> 4-1 = 3

In [38]:
ohe = OneHotEncoder(drop="first", sparse_output=False)

In [39]:
ohe_df = ohe.fit_transform(df[['gender', 'city', 'cough', 'has_covid']])
colums_name = ohe.get_feature_names_out()
new_df = pd.DataFrame(ohe_df, columns = colums_name)
new_df.head()

,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,cough_Strong,has_covid_Yes
0,1.0,0.0,1.0,0.0,0.0,0.0
1,1.0,1.0,0.0,0.0,0.0,1.0
2,1.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0

In [34]:
df = pd.concat((df, new_df), axis=1)
df.head()

,age,gender,fever,cough,city,has_covid,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,cough_Strong,has_covid_Yes
0,60,Male,103.0,Mild,Kolkata,No,1.0,0.0,1.0,0.0,0.0,0.0
1,27,Male,100.0,Mild,Delhi,Yes,1.0,1.0,0.0,0.0,0.0,1.0
2,42,Male,101.0,Mild,Delhi,No,1.0,1.0,0.0,0.0,0.0,0.0
3,31,Female,98.0,Mild,Kolkata,No,0.0,0.0,1.0,0.0,0.0,0.0
4,65,Female,101.0,Mild,Mumbai,No,0.0,0.0,0.0,1.0,0.0,0.0

In [35]:
df = df.drop(columns= ['gender', 'cough', 'city', 'has_covid'])
df.head()

,age,fever,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,cough_Strong,has_covid_Yes
0,60,103.0,1.0,0.0,1.0,0.0,0.0,0.0
1,27,100.0,1.0,1.0,0.0,0.0,0.0,1.0
2,42,101.0,1.0,1.0,0.0,0.0,0.0,0.0
3,31,98.0,0.0,0.0,1.0,0.0,0.0,0.0
4,65,101.0,0.0,0.0,0.0,1.0,0.0,0.0

## pd.get_dummies()

In [49]:
df = pd.read_csv("Data/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [50]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [51]:
df_enc = pd.get_dummies(df, columns= ['gender','cough', 'city', 'has_covid'], drop_first=True)
df_enc = df_enc.astype(int)
df_enc.head()

,age,fever,gender_Male,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,60,103,1,0,0,1,0,0
1,27,100,1,0,1,0,0,1
2,42,101,1,0,1,0,0,0
3,31,98,0,0,0,1,0,0
4,65,101,0,0,0,0,1,0

In [52]:
import pickle

with open('encoder.pkl', 'wb') as file:
    pickle.dump(ohe, file)

In [53]:
with open('encoder.pkl', 'rb') as file:
    encoder = pickle.load(file)