In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../Data\Churn_Modelling - Churn_Modelling.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Syed\AppData\Local\Temp\ipykernel_6680\448122799.py:1: SyntaxWarning: invalid escape sequence '\C'
  df = pd.read_csv('../Data\Churn_Modelling - Churn_Modelling.csv')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.drop(columns= ['Surname'])

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [6]:
df=df.drop(columns= ['Surname','RowNumber','CustomerId'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False)
oneHot = ohe.fit_transform(df[['Geography','Gender']])

col_name = ohe.get_feature_names_out()
new_df=pd.DataFrame(oneHot, columns= col_name)

In [9]:
new_df.head()

   Geography_Germany  Geography_Spain  Gender_Male
0                0.0              0.0          0.0
1                0.0              1.0          0.0
2                0.0              0.0          0.0
3                0.0              0.0          0.0
4                0.0              1.0          0.0

In [10]:
df= pd.concat((df,new_df), axis=1)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.0,0.0,0.0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0,0.0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0,0.0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.0,0.0,0.0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0,0.0

In [11]:
df=df.drop(columns= ['Geography','Gender'])
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,0.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0,0.0

In [13]:
df=pd.read_csv(r'../Data\Churn_Modelling - Churn_Modelling.csv')

In [15]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [20]:
df= df.drop(columns= ['Surname'])

In [25]:
from sklearn.preprocessing import OneHotEncoder

OneHot =OneHotEncoder(drop='first',sparse_output=False)
ohe = OneHot.fit_transform(df[['Geography','Gender']])

col_name = OneHot.get_feature_names_out()
new_df=pd.DataFrame(ohe, columns= col_name)

In [27]:
new_df.head()

   Geography_Germany  Geography_Spain  Gender_Male
0                0.0              0.0          0.0
1                0.0              1.0          0.0
2                0.0              0.0          0.0
3                0.0              0.0          0.0
4                0.0              1.0          0.0

In [29]:
df=pd.concat((df,new_df), axis=1)

df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.0,0.0,0.0
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0,0.0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0,0.0
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.0,0.0,0.0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0,0.0

In [30]:
df.drop(columns= ['Geography','Gender'])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1,0.0,0.0,0.0
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0,0.0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0,0.0
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0,0.0,0.0,0.0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0,0.0,0.0,1.0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0,0.0,0.0,1.0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1,0.0,0.0,0.0
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1,1.0,0.0,1.0
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0,0.0,0.0,0.0