## standard Scaler

In [7]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv(r"Data\Churn_Modelling - Churn_Modelling.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Data\\Churn_Modelling - Churn_Modelling.csv'

In [ ]:
df= df.drop(columns= ['Surname'])
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  str
 4   Gender           10000 non-null  str
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(2)
memory usage: 1015.8 KB

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

### with label encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['Geography'] = lb.fit_transform(df['Geography'])

In [ ]:
df['Gender'] = lb.fit_transform(df['Gender'])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  int64
 4   Gender           10000 non-null  int64
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(11)
memory usage: 1015.8 KB

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df_scaled = scaler.fit_transform(df)

In [ ]:
df= pd.DataFrame(df_scaled, columns = df.columns)

df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,-1.731878,-0.783213,-0.326221,-0.901886,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165
1,-1.731531,-0.606534,-0.440036,1.515067,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775
2,-1.731185,-0.995885,-1.536794,-0.901886,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165
3,-1.730838,0.144767,0.501521,-0.901886,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775
4,-1.730492,0.652659,2.063884,1.515067,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775

In [ ]:
np.round(df.describe(), 2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.73,-1.74,-3.11,-0.90,-1.10,-1.99,-1.73,-1.23,-0.91,-1.55,-1.03,-1.74,-0.51
25%,-0.87,-0.87,-0.69,-0.90,-1.10,-0.66,-0.70,-1.23,-0.91,-1.55,-1.03,-0.85,-0.51
50%,0.00,-0.00,0.02,-0.90,0.91,-0.18,-0.00,0.33,-0.91,0.65,0.97,0.00,-0.51
75%,0.87,0.87,0.70,0.31,0.91,0.48,0.69,0.82,0.81,0.65,0.97,0.86,-0.51
max,1.73,1.73,2.06,1.52,0.91,5.06,1.72,2.80,4.25,0.65,0.97,1.74,1.98

In [ ]:
df = pd.read_csv(r'Data\Attrition - Attrition.csv')

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [ ]:
cat_col = [col for col in df.columns if df[col].dtype == 'str']
print(cat_col ,'/n')

for col in cat_col:
    df[col] = lb.fit_transform(df[col])

df.info()

['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime'] /n
<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int64
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   int64
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   int64
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   int64
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   int64
 22  OverTime                  1470 non-null   int64
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(35)
memory usage: 402.1 KB

In [ ]:
df_scaled = scaler.fit_transform(df)

In [ ]:
df = pd.DataFrame(df_scaled, columns= df.columns)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.446350,2.280906,0.590048,0.742527,1.401512,-1.010909,-0.891688,-0.937414,0.0,-1.701283,...,-1.584178,0.0,-0.932014,-0.421642,-2.171982,-2.493820,-0.164613,-0.063296,-0.679146,0.245834
1,1.322365,-0.438422,-0.913194,-1.297775,-0.493817,-0.147150,-1.868426,-0.937414,0.0,-1.699621,...,1.191438,0.0,0.241988,-0.164511,0.155707,0.338096,0.488508,0.764998,-0.368715,0.806541
2,0.008343,2.280906,0.590048,1.414363,-0.493817,-0.887515,-0.891688,1.316673,0.0,-1.696298,...,-0.658973,0.0,-0.932014,-0.550208,0.155707,0.338096,-1.144294,-1.167687,-0.679146,-1.155935
3,-0.429664,-0.438422,-0.913194,1.461466,-0.493817,-0.764121,1.061787,-0.937414,0.0,-1.694636,...,0.266233,0.0,-0.932014,-0.421642,0.155707,0.338096,0.161947,0.764998,0.252146,-1.155935
4,-1.086676,-0.438422,0.590048,-0.524295,-0.493817,-0.887515,-1.868426,0.565311,0.0,-1.691313,...,1.191438,0.0,0.241988,-0.678774,0.155707,0.338096,-0.817734,-0.615492,-0.058285,-0.595227

In [ ]:
np.round(df.describe(),2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.0,1470.00,...,1470.00,1470.0,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00
mean,-0.00,0.00,-0.00,0.00,-0.00,0.00,0.00,0.00,0.0,-0.00,...,0.00,0.0,0.00,-0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.0,1.00,...,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.07,-0.44,-2.42,-1.74,-2.39,-1.01,-1.87,-1.69,0.0,-1.70,...,-1.58,0.0,-0.93,-1.45,-2.17,-2.49,-1.14,-1.17,-0.68,-1.16
25%,-0.76,-0.44,-0.91,-0.84,-0.49,-0.89,-0.89,-0.94,0.0,-0.89,...,-0.66,0.0,-0.93,-0.68,-0.62,-1.08,-0.65,-0.62,-0.68,-0.60
50%,-0.10,-0.44,0.59,-0.00,-0.49,-0.27,0.09,-0.19,0.0,-0.01,...,0.27,0.0,0.24,-0.16,0.16,0.34,-0.33,-0.34,-0.37,-0.31
75%,0.67,-0.44,0.59,0.88,1.40,0.59,1.06,0.57,0.0,0.88,...,1.19,0.0,0.24,0.48,0.16,0.34,0.33,0.76,0.25,0.81
max,2.53,2.28,0.59,1.73,1.40,2.44,2.04,2.07,0.0,1.73,...,1.19,0.0,2.59,3.69,2.48,1.75,5.39,3.80,3.98,3.61

In [ ]:
df = pd.read_csv(r'Data\Churn_Modelling - Churn_Modelling.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.drop(columns= ['Surname'])

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df['Geography'].unique()

<StringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str

In [ ]:
df['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['France','Spain','Germany'],['Female','Male']])
df[['Geography','Gender']]=ord.fit_transform(df[['Geography','Gender']])

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,0.0,0.0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,1.0,0.0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,0.0,0.0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,0.0,0.0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,1.0,0.0,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df = pd.read_csv(r'Data\covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df['gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [ ]:
df['city'].unique()

<StringArray>
['Kolkata', 'Delhi', 'Mumbai', 'Bangalore']
Length: 4, dtype: str

In [ ]:
df['has_covid'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [ ]:
df['cough'].unique()

<StringArray>
['Mild', 'Strong']
Length: 2, dtype: str

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['Male','Female'],['Mild','Strong'],['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'],['No', 'Yes']])
df[['gender','cough','city','has_covid']]=ord.fit_transform(df[['gender','cough','city','has_covid']])

In [ ]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60     0.0  103.0    0.0   0.0        0.0
1   27     0.0  100.0    0.0   1.0        1.0
2   42     0.0  101.0    0.0   1.0        0.0
3   31     1.0   98.0    0.0   0.0        0.0
4   65     1.0  101.0    0.0   2.0        0.0

In [ ]:
df = pd.read_csv("../Data/placement.csv")
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [ ]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

MinMax = MinMaxScaler()

x = MinMax.fit_transform(df)

df = pd.DataFrame(x, columns= df.columns)
df

        cgpa  resume_score  placed
0   0.694915      0.381995     1.0
1   0.217918      0.053528     0.0
2   0.726392      0.951338     1.0
3   0.389831      0.564477     1.0
4   0.544794      0.571776     1.0
..       ...           ...     ...
95  0.256659      0.347932     0.0
96  0.716707      0.683698     1.0
97  0.334140      0.688564     0.0
98  0.694915      0.165450     1.0
99  0.198547      0.403893     0.0

[100 rows x 3 columns]

In [ ]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv(r"../Data/covid_toy.csv")

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [13]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [16]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      100 non-null    float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [21]:
df['has_covid'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [22]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['Male','Female'],['Mild','Strong'],['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'],['No', 'Yes']])
df[['gender','cough','city','has_covid']]=ord.fit_transform(df[['gender','cough','city','has_covid']])

In [23]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60     0.0  103.0    0.0   0.0        0.0
1   27     0.0  100.0    0.0   1.0        1.0
2   42     0.0  101.0    0.0   1.0        0.0
3   31     1.0   98.0    0.0   0.0        0.0
4   65     1.0  101.0    0.0   2.0        0.0